DB Explorer: fix `explorer.draw()` race condition
pwntester/codeql.nvim pull request #33
Opened 2022-06-23 02:20 UTC by jorgectf

Reproduction:

* Set a database from the neo-tree panel
* Explorer loads fine
* Set another database from the neo-tree panel
* Explorer draws former database, because `explorer.draw()` happens before `config.database = database` in `queryserver.register_database(_)`.

2022-06-23 08:01 UTC, pwntester requested changes

2022-06-23 19:41 UTC, jorgectf commented on lua/codeql/init.lua
> +    end
I agree, done :D

2022-06-23 19:46 UTC, pwntester commented on lua/codeql/init.lua
> +    end
Why undoing the "o" mapping change? Do you need to rebase?

2022-06-24 07:50 UTC, merged

2022-06-24 07:50 UTC, pwntester commented
Great! thanks for the contribution!